Document: medes
Title: Debian medes Manual
Author: <insert document author here>
Abstract: This manual describes what medes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/medes/medes.sgml.gz

Format: postscript
Files: /usr/share/doc/medes/medes.ps.gz

Format: text
Files: /usr/share/doc/medes/medes.text.gz

Format: HTML
Index: /usr/share/doc/medes/html/index.html
Files: /usr/share/doc/medes/html/*.html

  
