#ifndef NATIVE_DEFINED
#define NATIVE_DEFINED

/*
 * Warning! This file is auto-generated by CMake,
 * Please ensure you are editing include/Native.h.gen.
 */

// The location of the application resources
#define APP_RESOURCE_PATH "/usr/local/share/medes"

#endif
